import basicLLops as LL

llist=LL.LinkedList()
llist.append(7)
llist.append(10)
llist.append(9)
llist.append(20)
llist.addatfront(1)
llist.traverse()
print(end="----------------------------\n")
llist.deleteval(1)
llist.traverse()
print(end="----------------------------\n")
llist.deletetatposition(3)
llist.traverse()
print(end="----------------------------\n")
print(llist.length())
print(end="----------------------------\n")
llist.reversingList()
llist.traverse()
